from django.core.management import BaseCommand

from sacco.models import Customer


class Command(BaseCommand):
    def handle(self, *args, **options):
        customers = [{"first_name":"Donnamarie","last_name":"Okell","email":"dokell0@dot.gov","gender":"Female","weight":58,"dob":"2024-06-14"},
{"first_name":"Leigha","last_name":"Wolfer","email":"lwolfer1@liveinternet.ru","gender":"Female","weight":92,"dob":"2014-03-17"},
{"first_name":"Shirline","last_name":"Wennam","email":"swennam2@amazon.com","gender":"Female","weight":64,"dob":"2014-09-02"},
{"first_name":"Melisenda","last_name":"Inglish","email":"minglish3@cmu.edu","gender":"Female","weight":60,"dob":"2020-10-14"},
{"first_name":"Hedwiga","last_name":"Cosby","email":"hcosby4@artisteer.com","gender":"Female","weight":82,"dob":"2021-12-29"},
{"first_name":"Brockie","last_name":"Spradbery","email":"bspradbery5@zimbio.com","gender":"Male","weight":65,"dob":"2013-08-14"},
{"first_name":"Kelly","last_name":"Tottman","email":"ktottman6@nhs.uk","gender":"Female","weight":40,"dob":"2021-06-13"},
{"first_name":"Mariele","last_name":"Lamberts","email":"mlamberts7@vk.com","gender":"Female","weight":63,"dob":"2020-09-29"},
{"first_name":"Doralynn","last_name":"Hundall","email":"dhundall8@europa.eu","gender":"Female","weight":46,"dob":"2022-12-09"},
{"first_name":"Lida","last_name":"Hastler","email":"lhastler9@wix.com","gender":"Female","weight":49,"dob":"2019-11-04"},
{"first_name":"Annabelle","last_name":"Yemm","email":"ayemma@blogtalkradio.com","gender":"Female","weight":63,"dob":"2013-06-04"},
{"first_name":"Jobye","last_name":"Lickorish","email":"jlickorishb@yahoo.co.jp","gender":"Female","weight":56,"dob":"2014-12-11"},
{"first_name":"Emile","last_name":"Bartkiewicz","email":"ebartkiewiczc@weather.com","gender":"Male","weight":42,"dob":"2018-10-01"},
{"first_name":"Cherianne","last_name":"Chaston","email":"cchastond@51.la","gender":"Female","weight":96,"dob":"2019-06-12"},
{"first_name":"Rhonda","last_name":"Meakes","email":"rmeakese@boston.com","gender":"Female","weight":70,"dob":"2015-02-05"},
{"first_name":"Brion","last_name":"Burgott","email":"bburgottf@usda.gov","gender":"Male","weight":80,"dob":"2019-01-20"},
{"first_name":"Clerc","last_name":"Wagge","email":"cwaggeg@123-reg.co.uk","gender":"Male","weight":74,"dob":"2023-11-26"},
{"first_name":"Ranna","last_name":"Shakelade","email":"rshakeladeh@ca.gov","gender":"Female","weight":82,"dob":"2021-12-06"},
{"first_name":"Humfrey","last_name":"Hrycek","email":"hhryceki@omniture.com","gender":"Male","weight":73,"dob":"2021-10-28"},
{"first_name":"Claudio","last_name":"Willock","email":"cwillockj@feedburner.com","gender":"Male","weight":78,"dob":"2017-12-16"},
{"first_name":"Nara","last_name":"Winchurst","email":"nwinchurstk@networkadvertising.org","gender":"Female","weight":80,"dob":"2023-01-11"},
{"first_name":"Hercule","last_name":"Crutch","email":"hcrutchl@topsy.com","gender":"Male","weight":73,"dob":"2023-04-15"},
{"first_name":"Borg","last_name":"Dornan","email":"bdornanm@webnode.com","gender":"Male","weight":40,"dob":"2021-03-16"},
{"first_name":"Bink","last_name":"Chalcroft","email":"bchalcroftn@pen.io","gender":"Male","weight":70,"dob":"2019-03-03"},
{"first_name":"Verena","last_name":"Ullyott","email":"vullyotto@qq.com","gender":"Female","weight":83,"dob":"2014-03-11"},
{"first_name":"Andy","last_name":"Terzo","email":"aterzop@japanpost.jp","gender":"Male","weight":93,"dob":"2019-10-21"},
{"first_name":"Jessie","last_name":"Aykroyd","email":"jaykroydq@java.com","gender":"Female","weight":46,"dob":"2017-01-26"},
{"first_name":"Phil","last_name":"Darth","email":"pdarthr@chron.com","gender":"Male","weight":77,"dob":"2014-03-18"},
{"first_name":"Pauly","last_name":"Woltman","email":"pwoltmans@opera.com","gender":"Female","weight":55,"dob":"2020-12-16"},
{"first_name":"Damon","last_name":"O'Brollachain","email":"dobrollachaint@whitehouse.gov","gender":"Male","weight":79,"dob":"2017-04-29"},
{"first_name":"Jefferey","last_name":"Leyman","email":"jleymanu@google.com.au","gender":"Male","weight":42,"dob":"2020-10-03"},
{"first_name":"Kimbra","last_name":"Rangle","email":"kranglev@hubpages.com","gender":"Female","weight":62,"dob":"2015-07-23"},
{"first_name":"Michaela","last_name":"Meineck","email":"mmeineckw@cmu.edu","gender":"Female","weight":51,"dob":"2015-01-22"},
{"first_name":"Buiron","last_name":"Ellson","email":"bellsonx@adobe.com","gender":"Male","weight":84,"dob":"2022-07-30"},
{"first_name":"Steffie","last_name":"Plank","email":"splanky@wikispaces.com","gender":"Female","weight":57,"dob":"2022-11-11"},
{"first_name":"Pia","last_name":"Clitherow","email":"pclitherowz@chicagotribune.com","gender":"Female","weight":96,"dob":"2021-03-18"},
{"first_name":"Jemie","last_name":"Kenderdine","email":"jkenderdine10@wordpress.org","gender":"Female","weight":62,"dob":"2013-01-01"},
{"first_name":"Arny","last_name":"MacNeachtain","email":"amacneachtain11@chronoengine.com","gender":"Male","weight":43,"dob":"2017-05-30"},
{"first_name":"Matthaeus","last_name":"Durnian","email":"mdurnian12@nhs.uk","gender":"Male","weight":56,"dob":"2023-05-01"},
{"first_name":"Nita","last_name":"Nisius","email":"nnisius13@nba.com","gender":"Female","weight":94,"dob":"2018-11-15"},
{"first_name":"Patty","last_name":"Woodier","email":"pwoodier14@opensource.org","gender":"Female","weight":72,"dob":"2013-01-02"},
{"first_name":"Buffy","last_name":"Hillum","email":"bhillum15@yale.edu","gender":"Female","weight":43,"dob":"2018-10-07"},
{"first_name":"Chrissie","last_name":"Kirkam","email":"ckirkam16@nyu.edu","gender":"Female","weight":91,"dob":"2017-09-16"},
{"first_name":"Maxie","last_name":"Keeffe","email":"mkeeffe17@cdc.gov","gender":"Male","weight":51,"dob":"2018-07-02"},
{"first_name":"Denver","last_name":"Quinnet","email":"dquinnet18@amazon.com","gender":"Male","weight":89,"dob":"2013-04-13"},
{"first_name":"Georgi","last_name":"McGerr","email":"gmcgerr19@plala.or.jp","gender":"Male","weight":68,"dob":"2013-04-22"},
{"first_name":"Geoffrey","last_name":"Dignum","email":"gdignum1a@bluehost.com","gender":"Male","weight":71,"dob":"2022-03-29"},
{"first_name":"Monique","last_name":"Markham","email":"mmarkham1b@boston.com","gender":"Female","weight":41,"dob":"2017-10-22"},
{"first_name":"Noam","last_name":"Willishire","email":"nwillishire1c@guardian.co.uk","gender":"Male","weight":85,"dob":"2014-12-12"},
{"first_name":"Hobie","last_name":"Syder","email":"hsyder1d@bbc.co.uk","gender":"Male","weight":63,"dob":"2015-09-07"},
{"first_name":"Christean","last_name":"Underdown","email":"cunderdown1e@parallels.com","gender":"Female","weight":72,"dob":"2023-08-24"},
{"first_name":"Guinna","last_name":"Khomishin","email":"gkhomishin1f@bing.com","gender":"Female","weight":74,"dob":"2021-02-02"},
{"first_name":"Talyah","last_name":"Verrall","email":"tverrall1g@va.gov","gender":"Female","weight":59,"dob":"2019-04-15"},
{"first_name":"Gigi","last_name":"Parnell","email":"gparnell1h@va.gov","gender":"Female","weight":60,"dob":"2020-05-23"},
{"first_name":"Devin","last_name":"Harberer","email":"dharberer1i@sohu.com","gender":"Male","weight":64,"dob":"2022-12-01"},
{"first_name":"Sheffield","last_name":"Ratke","email":"sratke1j@psu.edu","gender":"Male","weight":74,"dob":"2019-03-23"},
{"first_name":"Jessika","last_name":"Ovitz","email":"jovitz1k@issuu.com","gender":"Female","weight":48,"dob":"2018-08-04"},
{"first_name":"Jorie","last_name":"Kobsch","email":"jkobsch1l@prnewswire.com","gender":"Female","weight":72,"dob":"2015-01-03"},
{"first_name":"Natal","last_name":"Laddle","email":"nladdle1m@stumbleupon.com","gender":"Male","weight":66,"dob":"2013-01-01"},
{"first_name":"Adriane","last_name":"Rosiello","email":"arosiello1n@ca.gov","gender":"Female","weight":62,"dob":"2019-05-04"},
{"first_name":"Franchot","last_name":"Vaissiere","email":"fvaissiere1o@networkadvertising.org","gender":"Male","weight":52,"dob":"2017-02-12"},
{"first_name":"Jervis","last_name":"Debold","email":"jdebold1p@a8.net","gender":"Male","weight":41,"dob":"2022-12-26"},
{"first_name":"Albina","last_name":"Woolpert","email":"awoolpert1q@posterous.com","gender":"Female","weight":78,"dob":"2016-11-25"},
{"first_name":"Lenard","last_name":"Pearcehouse","email":"lpearcehouse1r@symantec.com","gender":"Male","weight":41,"dob":"2020-01-05"},
{"first_name":"Pip","last_name":"Brewer","email":"pbrewer1s@constantcontact.com","gender":"Male","weight":82,"dob":"2021-01-08"},
{"first_name":"Cyndie","last_name":"Keller","email":"ckeller1t@netscape.com","gender":"Female","weight":48,"dob":"2017-08-19"},
{"first_name":"Keir","last_name":"Raxworthy","email":"kraxworthy1u@ucla.edu","gender":"Male","weight":50,"dob":"2013-10-04"},
{"first_name":"Kris","last_name":"McGhee","email":"kmcghee1v@psu.edu","gender":"Male","weight":45,"dob":"2017-04-12"},
{"first_name":"Annaliese","last_name":"Swett","email":"aswett1w@msn.com","gender":"Female","weight":77,"dob":"2017-06-11"},
{"first_name":"Joly","last_name":"O'Kelly","email":"jokelly1x@narod.ru","gender":"Female","weight":90,"dob":"2018-01-25"},
{"first_name":"Cornelia","last_name":"Letteresse","email":"cletteresse1y@state.gov","gender":"Female","weight":80,"dob":"2013-08-08"},
{"first_name":"Georges","last_name":"Davio","email":"gdavio1z@archive.org","gender":"Male","weight":62,"dob":"2021-08-11"},
{"first_name":"Maure","last_name":"Bordiss","email":"mbordiss20@prlog.org","gender":"Female","weight":94,"dob":"2019-10-20"},
{"first_name":"Marlo","last_name":"Birtle","email":"mbirtle21@opensource.org","gender":"Female","weight":77,"dob":"2018-12-03"},
{"first_name":"Cornell","last_name":"Bernaert","email":"cbernaert22@ca.gov","gender":"Male","weight":44,"dob":"2021-03-23"},
{"first_name":"Fletch","last_name":"Cartwright","email":"fcartwright23@i2i.jp","gender":"Male","weight":46,"dob":"2013-12-27"},
{"first_name":"Odelle","last_name":"Dranfield","email":"odranfield24@webnode.com","gender":"Female","weight":83,"dob":"2024-03-08"},
{"first_name":"Rachel","last_name":"Getten","email":"rgetten25@lulu.com","gender":"Female","weight":46,"dob":"2015-01-06"},
{"first_name":"Gwennie","last_name":"Hambric","email":"ghambric26@wufoo.com","gender":"Female","weight":76,"dob":"2013-07-07"},
{"first_name":"Jeromy","last_name":"Molineux","email":"jmolineux27@smh.com.au","gender":"Male","weight":95,"dob":"2022-11-02"},
{"first_name":"Stern","last_name":"Gorini","email":"sgorini28@upenn.edu","gender":"Male","weight":68,"dob":"2015-05-25"},
{"first_name":"Barbi","last_name":"Noblet","email":"bnoblet29@washingtonpost.com","gender":"Female","weight":77,"dob":"2016-03-02"},
{"first_name":"Merissa","last_name":"Bohl","email":"mbohl2a@jugem.jp","gender":"Female","weight":53,"dob":"2019-06-24"},
{"first_name":"Nicolais","last_name":"Brookwell","email":"nbrookwell2b@feedburner.com","gender":"Male","weight":59,"dob":"2014-01-26"},
{"first_name":"Marlow","last_name":"Wolledge","email":"mwolledge2c@cafepress.com","gender":"Male","weight":44,"dob":"2014-02-08"},
{"first_name":"Georgena","last_name":"Ethington","email":"gethington2d@paypal.com","gender":"Female","weight":57,"dob":"2020-08-29"},
{"first_name":"Hughie","last_name":"Leavy","email":"hleavy2e@google.it","gender":"Male","weight":65,"dob":"2013-06-15"},
{"first_name":"Lazaro","last_name":"Geary","email":"lgeary2f@japanpost.jp","gender":"Male","weight":54,"dob":"2019-01-09"},
{"first_name":"Brittne","last_name":"Hayzer","email":"bhayzer2g@chronoengine.com","gender":"Female","weight":41,"dob":"2021-10-08"},
{"first_name":"Timmy","last_name":"Horche","email":"thorche2h@parallels.com","gender":"Male","weight":82,"dob":"2018-01-27"},
{"first_name":"Alfons","last_name":"Wall","email":"awall2i@microsoft.com","gender":"Male","weight":56,"dob":"2016-07-05"},
{"first_name":"Pierrette","last_name":"Rittelmeyer","email":"prittelmeyer2j@merriam-webster.com","gender":"Female","weight":72,"dob":"2024-09-01"},
{"first_name":"Rubina","last_name":"Spellacy","email":"rspellacy2k@youku.com","gender":"Female","weight":89,"dob":"2022-11-25"},
{"first_name":"Anica","last_name":"Whiscard","email":"awhiscard2l@sitemeter.com","gender":"Female","weight":57,"dob":"2022-02-08"},
{"first_name":"Reina","last_name":"Torr","email":"rtorr2m@1688.com","gender":"Female","weight":73,"dob":"2019-12-03"},
{"first_name":"Skyler","last_name":"Sainz","email":"ssainz2n@nifty.com","gender":"Male","weight":91,"dob":"2021-10-04"},
{"first_name":"Barron","last_name":"Nicolls","email":"bnicolls2o@e-recht24.de","gender":"Male","weight":55,"dob":"2021-10-06"},
{"first_name":"Kizzie","last_name":"Littefair","email":"klittefair2p@hubpages.com","gender":"Female","weight":66,"dob":"2020-07-11"},
{"first_name":"Coleman","last_name":"Pascoe","email":"cpascoe2q@miitbeian.gov.cn","gender":"Male","weight":52,"dob":"2015-03-03"},
{"first_name":"Caspar","last_name":"Seaborne","email":"cseaborne2r@ucla.edu","gender":"Male","weight":77,"dob":"2014-12-12"}]
        for c in customers:
            customer = Customer(**c)
            customer.save()

        self.stdout.write(
            self.style.SUCCESS('Successfuly populated customers')
        )

        # python manage.py populate