from django.core.management import BaseCommand

from sacco.models import Customer


class Command(BaseCommand):
    def handle(self, *args, **options):
        customers = [{"first_name":"Remy","last_name":"Doveston","email":"rdoveston0@over-blog.com","gender":"Female","weight":40,"dob":"2/11/2024"},
{"first_name":"Barbaraanne","last_name":"Britch","email":"bbritch1@boston.com","gender":"Female","weight":93,"dob":"9/11/2017"},
{"first_name":"Elmore","last_name":"Wrotham","email":"ewrotham2@sina.com.cn","gender":"Male","weight":64,"dob":"10/8/2020"},
{"first_name":"Alexandros","last_name":"Hryncewicz","email":"ahryncewicz3@cnn.com","gender":"Male","weight":85,"dob":"5/8/2022"},
{"first_name":"Addy","last_name":"Madgwick","email":"amadgwick4@marketwatch.com","gender":"Male","weight":44,"dob":"3/31/2018"},
{"first_name":"Crosby","last_name":"Powdrell","email":"cpowdrell5@yolasite.com","gender":"Male","weight":58,"dob":"6/6/2022"},
{"first_name":"Silvanus","last_name":"Uvedale","email":"suvedale6@cdbaby.com","gender":"Male","weight":69,"dob":"3/25/2022"},
{"first_name":"Angelo","last_name":"Colling","email":"acolling7@china.com.cn","gender":"Male","weight":48,"dob":"8/24/2021"},
{"first_name":"Marylynne","last_name":"Leroy","email":"mleroy8@alexa.com","gender":"Female","weight":57,"dob":"2/15/2021"},
{"first_name":"Brose","last_name":"D'eathe","email":"bdeathe9@imageshack.us","gender":"Male","weight":88,"dob":"10/27/2024"},
{"first_name":"Natty","last_name":"Peplay","email":"npeplaya@cdbaby.com","gender":"Female","weight":72,"dob":"10/22/2017"},
{"first_name":"Margaret","last_name":"Cawthra","email":"mcawthrab@ameblo.jp","gender":"Female","weight":42,"dob":"9/19/2021"},
{"first_name":"Jacintha","last_name":"Peniello","email":"jpenielloc@blinklist.com","gender":"Female","weight":90,"dob":"11/1/2022"},
{"first_name":"Dalli","last_name":"Cund","email":"dcundd@blog.com","gender":"Male","weight":45,"dob":"3/19/2016"},
{"first_name":"Stormie","last_name":"Kubasek","email":"skubaseke@quantcast.com","gender":"Female","weight":47,"dob":"11/4/2022"},
{"first_name":"Marcella","last_name":"Wardle","email":"mwardlef@discuz.net","gender":"Female","weight":67,"dob":"4/19/2019"},
{"first_name":"Corenda","last_name":"Clewley","email":"cclewleyg@earthlink.net","gender":"Female","weight":55,"dob":"11/10/2016"},
{"first_name":"Janenna","last_name":"Goodanew","email":"jgoodanewh@theatlantic.com","gender":"Female","weight":66,"dob":"7/24/2018"},
{"first_name":"Nester","last_name":"McClifferty","email":"nmccliffertyi@deviantart.com","gender":"Male","weight":45,"dob":"2/14/2018"},
{"first_name":"Nicolina","last_name":"Hargreaves","email":"nhargreavesj@pagesperso-orange.fr","gender":"Female","weight":63,"dob":"1/12/2014"},
{"first_name":"Irving","last_name":"Paolozzi","email":"ipaolozzik@slate.com","gender":"Male","weight":85,"dob":"2/8/2023"},
{"first_name":"Dora","last_name":"O'Kynsillaghe","email":"dokynsillaghel@ask.com","gender":"Female","weight":92,"dob":"4/24/2023"},
{"first_name":"Travus","last_name":"Glitherow","email":"tglitherowm@typepad.com","gender":"Male","weight":78,"dob":"5/25/2024"},
{"first_name":"Hasheem","last_name":"Frankham","email":"hfrankhamn@blinklist.com","gender":"Male","weight":92,"dob":"10/3/2016"},
{"first_name":"Nydia","last_name":"Upstone","email":"nupstoneo@netlog.com","gender":"Female","weight":43,"dob":"12/7/2015"},
{"first_name":"Zechariah","last_name":"Skelhorn","email":"zskelhornp@ucoz.com","gender":"Male","weight":59,"dob":"10/19/2017"},
{"first_name":"Beverlee","last_name":"Halbeard","email":"bhalbeardq@irs.gov","gender":"Female","weight":54,"dob":"6/25/2024"},
{"first_name":"Hunter","last_name":"Whoston","email":"hwhostonr@angelfire.com","gender":"Male","weight":86,"dob":"5/10/2014"},
{"first_name":"Rip","last_name":"Flear","email":"rflears@java.com","gender":"Male","weight":89,"dob":"1/7/2013"},
{"first_name":"Lira","last_name":"Warry","email":"lwarryt@cyberchimps.com","gender":"Female","weight":66,"dob":"2/16/2020"},
{"first_name":"Zia","last_name":"Farra","email":"zfarrau@unc.edu","gender":"Female","weight":96,"dob":"4/22/2017"},
{"first_name":"Leland","last_name":"Cartmer","email":"lcartmerv@si.edu","gender":"Male","weight":59,"dob":"7/8/2022"},
{"first_name":"Wynny","last_name":"Condie","email":"wcondiew@youtu.be","gender":"Female","weight":91,"dob":"1/13/2023"},
{"first_name":"Quinn","last_name":"Ridgley","email":"qridgleyx@foxnews.com","gender":"Female","weight":92,"dob":"4/23/2020"},
{"first_name":"Kipp","last_name":"Duckerin","email":"kduckeriny@wordpress.com","gender":"Male","weight":43,"dob":"12/27/2018"},
{"first_name":"Jori","last_name":"Blaxeland","email":"jblaxelandz@fc2.com","gender":"Female","weight":81,"dob":"11/23/2013"},
{"first_name":"Meade","last_name":"Gorden","email":"mgorden10@redcross.org","gender":"Male","weight":55,"dob":"5/19/2020"},
{"first_name":"Friedrick","last_name":"Dalgarno","email":"fdalgarno11@apple.com","gender":"Male","weight":59,"dob":"8/10/2019"},
{"first_name":"Basile","last_name":"Cubbini","email":"bcubbini12@dropbox.com","gender":"Male","weight":51,"dob":"7/20/2020"},
{"first_name":"Aridatha","last_name":"Bunch","email":"abunch13@sohu.com","gender":"Female","weight":45,"dob":"11/6/2022"},
{"first_name":"Erica","last_name":"Yalden","email":"eyalden14@zimbio.com","gender":"Female","weight":61,"dob":"10/24/2024"},
{"first_name":"Catha","last_name":"Whittingham","email":"cwhittingham15@ucoz.com","gender":"Female","weight":90,"dob":"8/5/2020"},
{"first_name":"Hannis","last_name":"Durham","email":"hdurham16@mediafire.com","gender":"Female","weight":93,"dob":"2/16/2018"},
{"first_name":"Chrissy","last_name":"Annion","email":"cannion17@51.la","gender":"Male","weight":79,"dob":"6/2/2015"},
{"first_name":"Tisha","last_name":"Linguard","email":"tlinguard18@ow.ly","gender":"Female","weight":52,"dob":"5/18/2016"},
{"first_name":"Sonya","last_name":"Neubigging","email":"sneubigging19@microsoft.com","gender":"Female","weight":69,"dob":"1/7/2024"},
{"first_name":"Killian","last_name":"Lenihan","email":"klenihan1a@ibm.com","gender":"Male","weight":41,"dob":"8/14/2024"},
{"first_name":"Rivkah","last_name":"Chamberlaine","email":"rchamberlaine1b@baidu.com","gender":"Female","weight":59,"dob":"10/11/2019"},
{"first_name":"Marian","last_name":"Giacomucci","email":"mgiacomucci1c@exblog.jp","gender":"Female","weight":55,"dob":"3/1/2013"},
{"first_name":"Flossy","last_name":"Cammomile","email":"fcammomile1d@typepad.com","gender":"Female","weight":91,"dob":"10/20/2020"},
{"first_name":"Madel","last_name":"Benedetti","email":"mbenedetti1e@forbes.com","gender":"Female","weight":59,"dob":"6/23/2014"},
{"first_name":"Belia","last_name":"Shippam","email":"bshippam1f@jiathis.com","gender":"Female","weight":91,"dob":"8/25/2013"},
{"first_name":"Chris","last_name":"Rilton","email":"crilton1g@dmoz.org","gender":"Female","weight":60,"dob":"6/22/2018"},
{"first_name":"Kalina","last_name":"Gleader","email":"kgleader1h@tiny.cc","gender":"Female","weight":90,"dob":"1/27/2024"},
{"first_name":"Alberta","last_name":"Kolczynski","email":"akolczynski1i@princeton.edu","gender":"Female","weight":88,"dob":"5/29/2024"},
{"first_name":"Munmro","last_name":"Ratchford","email":"mratchford1j@cam.ac.uk","gender":"Male","weight":84,"dob":"11/12/2013"},
{"first_name":"Lona","last_name":"Desorts","email":"ldesorts1k@utexas.edu","gender":"Female","weight":78,"dob":"12/17/2016"},
{"first_name":"Dyana","last_name":"Capper","email":"dcapper1l@wix.com","gender":"Female","weight":49,"dob":"2/22/2021"},
{"first_name":"Delores","last_name":"Cattell","email":"dcattell1m@blogspot.com","gender":"Female","weight":76,"dob":"7/17/2022"},
{"first_name":"Rolando","last_name":"Lingwood","email":"rlingwood1n@sogou.com","gender":"Male","weight":78,"dob":"9/28/2022"},
{"first_name":"Delmar","last_name":"Leggett","email":"dleggett1o@businessinsider.com","gender":"Male","weight":63,"dob":"9/28/2018"},
{"first_name":"Leonore","last_name":"Malim","email":"lmalim1p@businessweek.com","gender":"Female","weight":84,"dob":"10/20/2016"},
{"first_name":"Shari","last_name":"Dunridge","email":"sdunridge1q@ustream.tv","gender":"Female","weight":70,"dob":"6/1/2023"},
{"first_name":"Ingeberg","last_name":"Surgison","email":"isurgison1r@salon.com","gender":"Female","weight":55,"dob":"8/26/2014"},
{"first_name":"Abra","last_name":"Trenoweth","email":"atrenoweth1s@desdev.cn","gender":"Female","weight":96,"dob":"4/13/2024"},
{"first_name":"Kurt","last_name":"Droogan","email":"kdroogan1t@wufoo.com","gender":"Male","weight":48,"dob":"4/29/2021"},
{"first_name":"Babara","last_name":"MacLennan","email":"bmaclennan1u@feedburner.com","gender":"Female","weight":77,"dob":"10/2/2019"},
{"first_name":"Filberto","last_name":"D'Alessio","email":"fdalessio1v@usnews.com","gender":"Male","weight":83,"dob":"8/7/2024"},
{"first_name":"Murray","last_name":"Broxis","email":"mbroxis1w@360.cn","gender":"Male","weight":61,"dob":"7/4/2023"},
{"first_name":"Renault","last_name":"Beecheno","email":"rbeecheno1x@technorati.com","gender":"Male","weight":74,"dob":"11/28/2023"},
{"first_name":"Vail","last_name":"Street","email":"vstreet1y@hubpages.com","gender":"Male","weight":83,"dob":"7/8/2021"},
{"first_name":"Reine","last_name":"Teas","email":"rteas1z@printfriendly.com","gender":"Female","weight":69,"dob":"12/19/2012"},
{"first_name":"Broddy","last_name":"Oliveira","email":"boliveira20@buzzfeed.com","gender":"Male","weight":70,"dob":"12/29/2017"},
{"first_name":"Saleem","last_name":"Oriel","email":"soriel21@dmoz.org","gender":"Male","weight":76,"dob":"9/14/2014"},
{"first_name":"Editha","last_name":"Harry","email":"eharry22@blogspot.com","gender":"Female","weight":40,"dob":"8/7/2019"},
{"first_name":"Baxie","last_name":"Roseburgh","email":"broseburgh23@nymag.com","gender":"Male","weight":65,"dob":"9/14/2013"},
{"first_name":"Damaris","last_name":"Kingswoode","email":"dkingswoode24@netvibes.com","gender":"Female","weight":65,"dob":"7/7/2021"},
{"first_name":"Ichabod","last_name":"Mulvagh","email":"imulvagh25@ehow.com","gender":"Male","weight":44,"dob":"11/23/2014"},
{"first_name":"Wilhelm","last_name":"Pellamont","email":"wpellamont26@timesonline.co.uk","gender":"Male","weight":53,"dob":"1/5/2014"},
{"first_name":"Esmaria","last_name":"Sandell","email":"esandell27@sitemeter.com","gender":"Female","weight":94,"dob":"4/9/2018"},
{"first_name":"Murielle","last_name":"Taffarello","email":"mtaffarello28@flavors.me","gender":"Female","weight":78,"dob":"4/15/2019"},
{"first_name":"Janet","last_name":"Calrow","email":"jcalrow29@geocities.com","gender":"Female","weight":61,"dob":"11/13/2024"},
{"first_name":"Faulkner","last_name":"Blodg","email":"fblodg2a@vkontakte.ru","gender":"Male","weight":90,"dob":"4/30/2016"},
{"first_name":"Perl","last_name":"Radmore","email":"pradmore2b@earthlink.net","gender":"Female","weight":63,"dob":"6/5/2014"},
{"first_name":"Leroi","last_name":"Robbeke","email":"lrobbeke2c@t-online.de","gender":"Male","weight":56,"dob":"3/26/2023"},
{"first_name":"Kaila","last_name":"Deveraux","email":"kdeveraux2d@w3.org","gender":"Female","weight":41,"dob":"9/5/2024"},
{"first_name":"Hillyer","last_name":"Vignaux","email":"hvignaux2e@globo.com","gender":"Male","weight":68,"dob":"1/1/2013"},
{"first_name":"Myra","last_name":"Isgar","email":"misgar2f@lulu.com","gender":"Female","weight":84,"dob":"12/12/2019"},
{"first_name":"Nicky","last_name":"Stolberger","email":"nstolberger2g@mediafire.com","gender":"Female","weight":95,"dob":"1/14/2019"},
{"first_name":"Rhody","last_name":"Crysell","email":"rcrysell2h@csmonitor.com","gender":"Female","weight":75,"dob":"9/20/2024"},
{"first_name":"Ogdon","last_name":"Alvis","email":"oalvis2i@wufoo.com","gender":"Male","weight":71,"dob":"7/28/2022"},
{"first_name":"Ker","last_name":"Vayne","email":"kvayne2j@clickbank.net","gender":"Male","weight":44,"dob":"5/9/2018"},
{"first_name":"Towney","last_name":"Shipcott","email":"tshipcott2k@psu.edu","gender":"Male","weight":70,"dob":"8/21/2016"},
{"first_name":"Marion","last_name":"Gianelli","email":"mgianelli2l@who.int","gender":"Female","weight":66,"dob":"8/4/2015"},
{"first_name":"Farlay","last_name":"Dillway","email":"fdillway2m@fc2.com","gender":"Male","weight":84,"dob":"10/26/2021"},
{"first_name":"Guglielmo","last_name":"Idney","email":"gidney2n@twitter.com","gender":"Male","weight":52,"dob":"9/10/2019"},
{"first_name":"Briano","last_name":"Weaver","email":"bweaver2o@mozilla.org","gender":"Male","weight":90,"dob":"10/15/2018"},
{"first_name":"Hartwell","last_name":"Dottrell","email":"hdottrell2p@redcross.org","gender":"Male","weight":71,"dob":"4/16/2013"},
{"first_name":"Ahmed","last_name":"Eastlake","email":"aeastlake2q@arizona.edu","gender":"Male","weight":55,"dob":"2/12/2014"},
{"first_name":"Kelsy","last_name":"Pennrington","email":"kpennrington2r@msn.com","gender":"Female","weight":83,"dob":"8/29/2023"}]
        for c in customers:
            customer = Customer(**c)
            customer.save()
        self.stdout.write(
            self.style.SUCCESS('Successfuly populated customers')
        )